name: mheads-yii-filestorage

services:
  php:
    build:
      context: ./..
      dockerfile: ./docker/Dockerfile
    image: mheads-yii-filestorage-php-test
    volumes:
      - ./..:/code
    command: tail -F anything
